import {
  boardFeePerLaunchPackageSchema,
  boardProfileSchema,
  evmAddressSchema,
  evmChainIdSchema,
  flashLaunchFeePerSchema,
  metadataUrlSchema,
} from '@schema/common';
import { z } from 'zod';

/**
 * API-WIRE schema for the based.bid EVM `/create-board` endpoint payload. Built
 * internally by `createEvmBoard` from validated `createEvmBoardSchema` (./sdk.ts)
 * input plus the derived `account` (from `PRIVATE_KEY`) and uploaded IPFS URLs for
 * `logoUrl` / `bannerUrl` / `metaUri` (in place of the sdk's local file paths).
 *
 * `flashLaunchFeePer` is top-level (not inside `fees`): it is the board's cut of DEX
 * volume fees generated by flash tokens launched through this board.
 */
export const createEvmBoardApiSchema = z.object({
  account: evmAddressSchema.describe(
    'Board owner wallet address, derived from PRIVATE_KEY',
  ),
  chainId: evmChainIdSchema,
  title: z
    .string()
    .min(1, 'Title is required')
    .max(48, 'Title must be 48 characters or less')
    .describe(
      'Board name/title, shown publicly and used as the board identifier (max 48 characters)',
    ),
  description: z
    .string()
    .min(1, 'Description is required')
    .max(1000, 'Description too long')
    .describe('Public description shown on the board page'),
  flashLaunchFeePer: flashLaunchFeePerSchema,
  fees: boardFeePerLaunchPackageSchema,
  logoUrl: metadataUrlSchema.describe('Uploaded logo image URL'),
  bannerUrl: metadataUrlSchema.describe('Uploaded banner image URL'),
  metaUri: metadataUrlSchema.describe('Uploaded board metadata JSON URL'),
  ...boardProfileSchema.shape,
});

export type CreateEvmBoardApi = z.infer<typeof createEvmBoardApiSchema>;
