import { DEFAULT_BOARD_FEES } from '@constants';
import z from 'zod';
import { numberStringSchema } from './numeric-string.schema';

/**
 * Percentage of DEX trading volume fees that the board owner earns from flash tokens
 * launched under this board. Distinct from the per-package `fees` schedule (listing /
 * buy / sell / finalize / after-launch), which applies mainly to LBP-style launches.
 *
 * Example: `"1"` = 1% of the DEX volume fee stream generated by flash-token projects
 * on this board is paid to the board.
 */
export const flashLaunchFeePerSchema = numberStringSchema(0, 100).describe(
  'Board cut (%) of DEX volume fees from flash tokens launched under this board. ' +
    'This is the share your board earns from trading volume on those flash projects — ' +
    'not a one-time listing fee. Use a numeric string such as "0.001" (0.001%) or "1" (1%). ' +
    'Set independently of the per-package `fees` array.',
);

/** Fee percentages a custom board charges tokens/LBPs launching under it. */
export const boardFeeSchema = z.object({
  listingFee: numberStringSchema(0, 10).describe(
    'One-time fee (%) charged to list a token/LBP under this board',
  ),
  listingReferralFee: numberStringSchema(0, 10).describe(
    'Referral cut (%) of the listing fee paid to whoever referred the launch',
  ),
  buyFeePer: numberStringSchema(0, 100).describe(
    'Fee (%) the board takes on each buy transaction',
  ),
  sellFeePer: numberStringSchema(0, 100).describe(
    'Fee (%) the board takes on each sell transaction',
  ),
  finalizeFeePer: numberStringSchema(0, 100).describe(
    'Fee (%) the board takes when an LBP sale finalizes/graduates',
  ),
  tradingFeeAfterLaunchPer: numberStringSchema(0, 100).describe(
    'Fee (%) the board takes on ongoing trades after LBP graduates',
  ),
});

/**
 * Per-launch-package fee schedule for a board: exactly 3 entries, indexed to match
 * `LaunchPackageType` (0 = BASED, 1 = SUPER_BASED, 2 = ULTRA_BASED). Defaults to
 * `DEFAULT_BOARD_FEES` when omitted.
 *
 * Does not include flash-token volume fees — those are configured once at the board
 * root via `flashLaunchFeePer`.
 */
export const boardFeePerLaunchPackageSchema = z
  .array(boardFeeSchema)
  .length(3)
  .optional()
  .default(DEFAULT_BOARD_FEES)
  .describe(
    'Fee schedule per launch package tier, array of exactly 3 (BASED, SUPER_BASED, ULTRA_BASED). ' +
      'Flash-token DEX volume share is set separately with top-level `flashLaunchFeePer`.',
  );
